#!/bin/sh

THIS=`readlink -f $0`
DIR=`dirname $THIS`
NAME=`basename $THIS`

export LD_LIBRARY_PATH=$DIR

WPACK="net.sourceforge.waters"
MEM1="-Xmx1024m"
MEM2=
EA=
ARGS=


for F in "$@"; do
    case $F in
    -Xmx*)
        MEM1="$F"
        ;;
    -Xss*)
        MEM2="$F"
        ;;
    -ea|-enableassertions)
	EA=-enableassertions
	;;
    *)
        ARGS="$ARGS \"$F\""
        ;;
    esac
done

eval java -cp "$DIR/Supremica.jar" $EA $MEM1 $MEM2 \
     $WPACK.model.analysis.cli.CommandLineTool @name $NAME "$ARGS" 

